export default {
  version: '0.0.0',
  main: 'server/app.js',
  scripts: {
    test: 'npm run lint && npm run jest',
    jest: 'jest',
    'jest-client': 'jest --testMatch **/__tests__/client/**/*.spec.js',
    'jest-server': 'jest --testMatch **/__tests__/server/**/*.spec.js',
    babel: 'babel server -d dist/server -s',
    copy: 'copyfiles package.json .env.defaults .env.schema dist',
    build: 'rimraf dist && npm run babel && npm run build-client && npm run copy',
    'build-client': 'webpack --env=production --define process.env.NODE_ENV="\'production\'"',
    lint: 'run-p lint-*',
    precommit: 'lint-staged',
    commitmsg: 'commitlint -e',
    'lint-server': 'eslint server --fix',
    'lint-client': 'eslint client --fix',
    'lint-tests': 'eslint __tests__ --fix',
    dev: 'run-p client-dev server-dev',
    'server-dev': 'nodemon --watch server --exec "babel-node" server/app.js',
    'client-dev': 'webpack-dev-server --open',
    prod: 'npm run build && node dist/server/app.js',
    'dev-docker': 'run-p client-dev-docker server-dev-docker',
    'client-dev-docker': 'webpack-dev-server --host 0.0.0.0 --watch-poll',
    'server-dev-docker': 'npm run server-dev -- -L'
  },
  private: true,
  engines: {
    node: '>=8'
  },
  'lint-staged': {
    '*.js': [
      'eslint --fix',
      'git add'
    ]
  },
  jest: {
    notify: true,
    testURL: 'http://localhost',
    setupTestFrameworkScriptFile: './node_modules/jest-enzyme/lib/index.js',
    collectCoverage: true,
    setupFiles: [
      './__tests__/client/setup.js',
      'jest-localstorage-mock'
    ],
    testMatch: ['**/__tests__/**/*.spec.js'],
    coverageThreshold: {
      global: {
        branches: 100,
        functions: 100,
        lines: 100,
        statements: 100
      }
    }
  },
  devDependencies: {
    '@commitlint/cli': '^7.0.0',
    '@commitlint/config-angular': '^7.0.1',
    axios: '^0.18.0',
    'babel-cli': '^6.26.0',
    'babel-eslint': '^8.2.6',
    'babel-jest': '^23.4.0',
    'babel-loader': '^7.1.5',
    'babel-minify-webpack-plugin': '^0.3.1',
    'babel-plugin-dynamic-import-node': '^2.0.0',
    'babel-plugin-lodash': '^3.3.4',
    'babel-plugin-syntax-dynamic-import': '^6.18.0',
    'babel-plugin-transform-es2015-modules-commonjs': '^6.26.2',
    'babel-plugin-transform-object-rest-spread': '^6.26.0',
    'babel-preset-env': '^1.7.0',
    'babel-preset-react': '^6.24.1',
    'babel-register': '^6.26.0',
    'compression-webpack-plugin': '^1.1.11',
    copyfiles: '^2.0.0',
    'css-loader': '^1.0.0',
    enzyme: '^3.3.0',
    'enzyme-adapter-react-16': '^1.1.1',
    eslint: '^5.2.0',
    'eslint-config-noamokman': '^8.0.1',
    'eslint-plugin-import': '^2.13.0',
    'eslint-plugin-jest': '^21.18.0',
    'eslint-plugin-lodash': '^2.7.0',
    'eslint-plugin-react': '^7.10.0',
    'eslint-plugin-unicorn': '^4.0.3',
    'file-loader': '^1.1.11',
    'html-webpack-plugin': '^3.2.0',
    husky: '^0.14.3',
    jest: '^23.4.1',
    'jest-enzyme': '^6.0.2',
    'jest-localstorage-mock': '^2.2.0',
    'lint-staged': '^7.2.0',
    'loadable-components': '^2.2.2',
    'material-ui': '^0.20.1',
    nodemon: '^1.18.3',
    'npm-run-all': '^4.1.3',
    plop: '^2.0.0',
    plur: '^3.0.1',
    'preload-webpack-plugin': '^2.3.0',
    'prop-types': '^15.6.2',
    raf: '^3.4.0',
    react: '^16.4.1',
    'react-collapse': '^4.0.3',
    'react-dom': '^16.4.1',
    'react-hot-loader': '^4.3.3',
    'react-motion': '^0.5.2',
    'react-redux': '^5.0.7',
    'react-router': '^3.0.0',
    'react-router-redux': '^4.0.8',
    'react-test-renderer': '^16.4.1',
    recompose: '^0.27.1',
    redux: '^4.0.0',
    'redux-actions': '^2.4.0',
    'redux-auth-wrapper': '^2.0.3',
    'redux-axios-middleware': '^4.0.0',
    'redux-devtools': '^3.4.1',
    'redux-devtools-dock-monitor': '^1.1.3',
    'redux-devtools-log-monitor': '^1.4.0',
    'redux-form': '^7.4.2',
    'redux-mock-store': '^1.5.3',
    'redux-simple-promise': '^2.0.2',
    'redux-sockets': '^1.1.1',
    reflexbox: '^3.0.1',
    rimraf: '^2.6.2',
    'socket.io-client': '^2.1.1',
    'style-loader': '^0.21.0',
    'styled-components': '^3.3.3',
    supertest: '^3.1.0',
    uppercamelcase: '^3.0.0',
    webpack: '^4.16.2',
    'webpack-cli': '^3.1.0',
    'webpack-dev-server': '^3.1.5'
  },
  dependencies: {
    'body-parser': '^1.18.3',
    bunyan: '^1.8.12',
    'bunyan-format': '^0.2.1',
    compression: '^1.7.3',
    'cookie-parser': '^1.4.3',
    'dotenv-extended': '^2.0.2',
    'email-address': '^1.2.2',
    'env-bunyan': '^0.1.0',
    express: '^4.16.3',
    'express-async-router': '^0.1.13',
    'express-json-error-handler': '^2.0.0',
    'express-jwt': '^5.3.1',
    'express-mongoose-errors': '^0.2.0',
    'express-param-objectid': '^1.0.0',
    'express-static-gzip': '^0.3.2',
    helmet: '^3.13.0',
    'http-errors': '^1.6.3',
    'http-reject-empty': '^1.0.0',
    'in-production': '^1.0.1',
    jsonwebtoken: '^8.3.0',
    lodash: '^4.17.10',
    'method-override': '^3.0.0',
    mongoose: '^5.2.4',
    'mongoose-plugin-seed': '^0.4.0',
    morgan: '^1.9.0',
    passport: '^0.4.0',
    'passport-local-mongoose': '^5.0.1',
    pify: '^3.0.0',
    'socket.io': '^2.1.1',
    'socketio-jwt': '^4.5.0'
  }
};